/* eslint-disable camelcase */
'use strict';

module.exports = (info, options) => ({
	alfred_workflow_name: info.name,
	alfred_workflow_version: info.version,
	alfred_uid: `alfred-${info.name}`,
	alfred_bundleId: info.bundleid,
	alfred_version: options.version || '3.0.3',
	alfred_theme: options.theme || 'theme.urlimport.153A3C58-B2D9-4F08-B342-B0BF7F6E8DE9',
	alfred_theme_background: options.theme_background || 'rgba(252,254,255,0.85)',
	alfred_theme_selection_background: options.theme_selection || 'rgba(255,255,255,0.26)',
	alfred_theme_subtext: options.theme_subtext || '0',
	alfred_workflow_data: options.workflow_data,
	alfred_workflow_cache: options.workflow_cache,
	alfred_preferences: '',
	alfred_preferences_localhash: '',
	alfred_debug: '1',

	arvis_version: '0.1',
	arvis_extension_bundleid: `${info.creator}.${info.name}`,
	arvis_extension_name: info.name,
	arvis_extension_version: info.version,
	arvis_extension_data: info.data,
	arvis_extension_cache: info.cache,
	arvis_extension_history: 'not supported',
	arvis_extension_type: info.type,
	arvis_platform_home: 'not supported',
	arvis_platform_cache: 'not supported',
	arvis_platform_crushDumps: 'not supported',
	arvis_platform_desktop: 'not supported',
	arvis_platform_documents: 'not supported',
	arvis_platform_downloads: 'not supported',
	arvis_platform_exe: 'not supported',
	arvis_platform_logs: 'not supported',
	arvis_platform_module: 'not supported',
	arvis_platform_music: 'not supported',
	arvis_platform_pictures: 'not supported',
	arvis_platform_temp: 'not supported',
	arvis_platform_userData: 'not supported',
	arvis_platform_appData: 'not supported',
	arvis_platform_videos: 'not supported',
	arvis_platform_recent: 'not supported',
});
